name: Integration Tests for Development API
permissions:
  contents: read

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  integration_tests:
    if: ${{ github.repository == 'nsls2/nsls2api' }}  # Do not run on forks
    runs-on: self-hosted

    steps:
    - name: Print hostname
      run: echo "The hostname is $(hostname)"
      
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        persist-credentials: false

    - name: Setup Java
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        distribution: 'zulu'
        java-version: '21'
    
    - name: Download ijhttp.zip 
      run: curl -f -L -o ijhttp.zip "https://jb.gg/ijhttp/latest"

    - name: Unzip ijhttp.zip
      run: unzip -q ijhttp.zip

    - name: Beamline endpoint tests
      run: |
        ./ijhttp/ijhttp --env-file ./integration-tests/http-client.env.json \
        --env dev \
        ./integration-tests/check_all_beamlines.http

    - name: Check API Service
      run: |
        ./ijhttp/ijhttp --env-file ./integration-tests/http-client.env.json \
        --env dev \
        ./integration-tests/check_service_health.http
